version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db/mydb
    depends_on:
      - db
