version: '3.5' 

services: 
    youtube-dl:  
      image: youtube-dl:latest
      build: . 
      volumes: 
        - downloads:/mydir
      container_name: youtube-dl

    volumes:
      downloads:
        driver: local

